//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources._", typeof(_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0} {1}] has been executed in result of citizen actions..
        /// </summary>
        public static string ABIsExecuted {
            get {
                return ResourceManager.GetString("ABIsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been killed by werewolves mercilessly..
        /// </summary>
        public static string AHasBeenKilledByWerewolves {
            get {
                return ResourceManager.GetString("AHasBeenKilledByWerewolves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is guarding {1} ....
        /// </summary>
        public static string AIsGuardingB {
            get {
                return ResourceManager.GetString("AIsGuardingB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacking [{0} {1}] ....
        /// </summary>
        public static string AttackingAB {
            get {
                return ResourceManager.GetString("AttackingAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack of Werewolves.
        /// </summary>
        public static string AttackOfWerewolves {
            get {
                return ResourceManager.GetString("AttackOfWerewolves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen Actions.
        /// </summary>
        public static string CitizenActions {
            get {
                return ResourceManager.GetString("CitizenActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dead told that {0} was {1}..
        /// </summary>
        public static string ItHasBeenProvedThatKilledAIsB {
            get {
                return ResourceManager.GetString("ItHasBeenProvedThatKilledAIsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody executed because of the insufficient number of votes..
        /// </summary>
        public static string NobodyExecutedBecauseOfInsufficientNumberOfVotes {
            get {
                return ResourceManager.GetString("NobodyExecutedBecauseOfInsufficientNumberOfVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody killed because of hunter&apos;s activity..
        /// </summary>
        public static string NobodyKilledBecauseOfHuntersActivity {
            get {
                return ResourceManager.GetString("NobodyKilledBecauseOfHuntersActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Random).
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
