//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources._", typeof(_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0} {1}] has been executed in result of citizen actions..
        /// </summary>
        public static string ABIsExecuted {
            get {
                return ResourceManager.GetString("ABIsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been killed by werewolves mercilessly..
        /// </summary>
        public static string AHasBeenKilledByWerewolves {
            get {
                return ResourceManager.GetString("AHasBeenKilledByWerewolves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has come as {1}..
        /// </summary>
        public static string AHasComeAsB {
            get {
                return ResourceManager.GetString("AHasComeAsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has gone from {1}..
        /// </summary>
        public static string AHasGoneFromB {
            get {
                return ResourceManager.GetString("AHasGoneFromB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined as {1}..
        /// </summary>
        public static string AHasJoinedAsB {
            get {
                return ResourceManager.GetString("AHasJoinedAsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is guarding {1} ....
        /// </summary>
        public static string AIsGuardingB {
            get {
                return ResourceManager.GetString("AIsGuardingB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your clear mind tells that {0} is a true friend of citizens..
        /// </summary>
        public static string AIsTrueFriendOfCitizens {
            get {
                return ResourceManager.GetString("AIsTrueFriendOfCitizens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} senses that {1} is {2} in result of a fortune-telling..
        /// </summary>
        public static string ASenseThatBIsC {
            get {
                return ResourceManager.GetString("ASenseThatBIsC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacking [{0} {1}] ....
        /// </summary>
        public static string AttackingAB {
            get {
                return ResourceManager.GetString("AttackingAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack of Werewolves.
        /// </summary>
        public static string AttackOfWerewolves {
            get {
                return ResourceManager.GetString("AttackOfWerewolves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen Actions.
        /// </summary>
        public static string CitizenActions {
            get {
                return ResourceManager.GetString("CitizenActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day {0} dawns..
        /// </summary>
        public static string DayADawns {
            get {
                return ResourceManager.GetString("DayADawns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} won..
        /// </summary>
        public static string FactionAWon {
            get {
                return ResourceManager.GetString("FactionAWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first victim has been found at the crack of dawn. The message of his last moment tells us that inhabitants are the following:.
        /// </summary>
        public static string FirstVictimFound {
            get {
                return ResourceManager.GetString("FirstVictimFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game has ended..
        /// </summary>
        public static string GameHasEnded {
            get {
                return ResourceManager.GetString("GameHasEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dead told that {0} was {1}..
        /// </summary>
        public static string ItHasBeenProvedThatKilledAIsB {
            get {
                return ResourceManager.GetString("ItHasBeenProvedThatKilledAIsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log can be downloaded from:.
        /// </summary>
        public static string LogCanBeDownloaded {
            get {
                return ResourceManager.GetString("LogCanBeDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matchmaking began..
        /// </summary>
        public static string MatchmakingBegan {
            get {
                return ResourceManager.GetString("MatchmakingBegan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody executed because of the insufficient number of votes..
        /// </summary>
        public static string NobodyExecutedBecauseOfInsufficientNumberOfVotes {
            get {
                return ResourceManager.GetString("NobodyExecutedBecauseOfInsufficientNumberOfVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody killed because of hunter&apos;s activity..
        /// </summary>
        public static string NobodyKilledBecauseOfHuntersActivity {
            get {
                return ResourceManager.GetString("NobodyKilledBecauseOfHuntersActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough actors to vote..
        /// </summary>
        public static string NotEnoughActorsToVote {
            get {
                return ResourceManager.GetString("NotEnoughActorsToVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul.actors{
        ///    margin: 0;
        ///    padding: 0;
        ///    list-style: none;
        ///}
        ///ul.actors li{
        ///    text-align: center;
        ///    width: 135px;
        ///    height: 64px;
        ///    float: left;
        ///    border: solid 1px #CCC;
        ///    white-space: nowrap;
        ///    overflow: hidden;
        ///}
        ///ul.actors li div.name{
        ///}
        ///ul.actors li table{
        ///    margin-left: auto;
        ///    margin-right: auto;
        ///}
        ///
        ///ul.messages{
        ///    margin: 0;
        ///    padding: 0;
        ///    list-style: none;
        ///}
        ///ul.messages li{
        ///    margin: 0;
        ///    padding: 9px 12px;
        ///    background: white;
        ///    bord [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PlayLogCSS {
            get {
                return ResourceManager.GetString("PlayLogCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Random).
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no werewolf..
        /// </summary>
        public static string ThereIsNoWerewolf {
            get {
                return ResourceManager.GetString("ThereIsNoWerewolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {1}, {0}! {2} players are chatting. {3} players are playing. {4} players are selecting characters..
        /// </summary>
        public static string WelcomeAToBChattingCPlayingDSelectingCharacterE {
            get {
                return ResourceManager.GetString("WelcomeAToBChattingCPlayingDSelectingCharacterE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a rumor that &quot;Werewolves&quot;; human-like predators have infiltrated into this town..
        /// </summary>
        public static string WerewolvesRumor {
            get {
                return ResourceManager.GetString("WerewolvesRumor", resourceCulture);
            }
        }
    }
}
