//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _EnumDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _EnumDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources._EnumDescription", typeof(_EnumDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Ghost Cat. Sided with Citizens. Kills one of Citizen Teams if executed. Kills one of Werewolves if attacked..
        /// </summary>
        public static string Role_Cat {
            get {
                return ResourceManager.GetString("Role_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A regular inhabitant. Sided with Citizens..
        /// </summary>
        public static string Role_Citizen {
            get {
                return ResourceManager.GetString("Role_Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A great werewolf. Attacks an inhabitant every night. Human for Fortune-tellers. Sided with Werewolves..
        /// </summary>
        public static string Role_ElderWolf {
            get {
                return ResourceManager.GetString("Role_ElderWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A traitor of humans. Sided with Werewolves. Knows who are Werewolves..
        /// </summary>
        public static string Role_Fanatic {
            get {
                return ResourceManager.GetString("Role_Fanatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A special citizen. Furtune-tells one inhabitant and knows his race..
        /// </summary>
        public static string Role_FortuneTeller {
            get {
                return ResourceManager.GetString("Role_FortuneTeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fox who disguised as a human. Dodges Werewolves&apos; attacks. Dies if fortune-telled. Sided with Foxes..
        /// </summary>
        public static string Role_Fox {
            get {
                return ResourceManager.GetString("Role_Fox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A special citizen. Guards one inhabitant from Werewolves&apos; attacks..
        /// </summary>
        public static string Role_Hunter {
            get {
                return ResourceManager.GetString("Role_Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the paired citizens. Sided with Citizens. Knows who is the partner. Ignores any private messages except from the partner. Becomes Hunter if partner has been killed by Werewolves. Suisides if partner has been executed. Always a pair of a male and a female..
        /// </summary>
        public static string Role_Lover {
            get {
                return ResourceManager.GetString("Role_Lover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role is not decided yet..
        /// </summary>
        public static string Role_None {
            get {
                return ResourceManager.GetString("Role_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A criminal hunter. Guards one inhabitant from Werewolves&apos; attacks. Werewolf for Fortune-tellers. Sided with Citizens..
        /// </summary>
        public static string Role_Poacher {
            get {
                return ResourceManager.GetString("Role_Poacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A traitor of humans. Sided with Werewolves. Does not know who are Werewolves..
        /// </summary>
        public static string Role_Psycho {
            get {
                return ResourceManager.GetString("Role_Psycho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A special citizen. Knows the race of the dead..
        /// </summary>
        public static string Role_Shaman {
            get {
                return ResourceManager.GetString("Role_Shaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An oriental priest who worships foxes as superior begings. Sided with Foxes..
        /// </summary>
        public static string Role_ShintoPriest {
            get {
                return ResourceManager.GetString("Role_ShintoPriest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A merciless creature. Attacks an inhabitant every night. Sided with Werewolves..
        /// </summary>
        public static string Role_Werewolf {
            get {
                return ResourceManager.GetString("Role_Werewolf", resourceCulture);
            }
        }
    }
}
