//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Enum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Enum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources._Enum", typeof(_Enum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen Team.
        /// </summary>
        public static string Faction_Citizen {
            get {
                return ResourceManager.GetString("Faction_Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fox Team.
        /// </summary>
        public static string Faction_Fox {
            get {
                return ResourceManager.GetString("Faction_Fox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Team.
        /// </summary>
        public static string Faction_None {
            get {
                return ResourceManager.GetString("Faction_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werewolf Team.
        /// </summary>
        public static string Faction_Werewolf {
            get {
                return ResourceManager.GetString("Faction_Werewolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo and bar!.
        /// </summary>
        public static string Foo_Bar {
            get {
                return ResourceManager.GetString("Foo_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Gender_None {
            get {
                return ResourceManager.GetString("Gender_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Mode_All {
            get {
                return ResourceManager.GetString("Mode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghost.
        /// </summary>
        public static string Mode_Ghost {
            get {
                return ResourceManager.GetString("Mode_Ghost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Mode_Private {
            get {
                return ResourceManager.GetString("Mode_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolf.
        /// </summary>
        public static string Mode_Wolf {
            get {
                return ResourceManager.GetString("Mode_Wolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fox.
        /// </summary>
        public static string Race_Fox {
            get {
                return ResourceManager.GetString("Race_Fox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string Race_Human {
            get {
                return ResourceManager.GetString("Race_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werewolf.
        /// </summary>
        public static string Race_Werewolf {
            get {
                return ResourceManager.GetString("Race_Werewolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        public static string Role_Cat {
            get {
                return ResourceManager.GetString("Role_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen.
        /// </summary>
        public static string Role_Citizen {
            get {
                return ResourceManager.GetString("Role_Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder Wolf.
        /// </summary>
        public static string Role_ElderWolf {
            get {
                return ResourceManager.GetString("Role_ElderWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fanatic.
        /// </summary>
        public static string Role_Fanatic {
            get {
                return ResourceManager.GetString("Role_Fanatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortune Teller.
        /// </summary>
        public static string Role_FortuneTeller {
            get {
                return ResourceManager.GetString("Role_FortuneTeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fox.
        /// </summary>
        public static string Role_Fox {
            get {
                return ResourceManager.GetString("Role_Fox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        public static string Role_Hunter {
            get {
                return ResourceManager.GetString("Role_Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lover.
        /// </summary>
        public static string Role_Lover {
            get {
                return ResourceManager.GetString("Role_Lover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Role.
        /// </summary>
        public static string Role_None {
            get {
                return ResourceManager.GetString("Role_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poacher.
        /// </summary>
        public static string Role_Poacher {
            get {
                return ResourceManager.GetString("Role_Poacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psycho.
        /// </summary>
        public static string Role_Psycho {
            get {
                return ResourceManager.GetString("Role_Psycho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaman.
        /// </summary>
        public static string Role_Shaman {
            get {
                return ResourceManager.GetString("Role_Shaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shinto Priest.
        /// </summary>
        public static string Role_ShintoPriest {
            get {
                return ResourceManager.GetString("Role_ShintoPriest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werewolf.
        /// </summary>
        public static string Role_Werewolf {
            get {
                return ResourceManager.GetString("Role_Werewolf", resourceCulture);
            }
        }
    }
}
