//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources._Error", typeof(_Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains ngword {1}..
        /// </summary>
        public static string AContainsNGWordB {
            get {
                return ResourceManager.GetString("AContainsNGWordB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1}..
        /// </summary>
        public static string AMustBeB {
            get {
                return ResourceManager.GetString("AMustBeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be bigger than {1}..
        /// </summary>
        public static string AMustBeBiggerThanB {
            get {
                return ResourceManager.GetString("AMustBeBiggerThanB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} to {2}..
        /// </summary>
        public static string AMustBeBToC {
            get {
                return ResourceManager.GetString("AMustBeBToC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} to {2} alphanumeric characters..
        /// </summary>
        public static string AMustBeBtoCAlphanumericCharacters {
            get {
                return ResourceManager.GetString("AMustBeBtoCAlphanumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} to {2} characters..
        /// </summary>
        public static string AMustBeBToCCharacters {
            get {
                return ResourceManager.GetString("AMustBeBToCCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} to {2} not-special, not-blank characters..
        /// </summary>
        public static string AMustBeBToCNonSpecialCharacters {
            get {
                return ResourceManager.GetString("AMustBeBToCNonSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be up to {1} characters or null..
        /// </summary>
        public static string AMustBeUpToBCharactersOrNull {
            get {
                return ResourceManager.GetString("AMustBeUpToBCharactersOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be minus..
        /// </summary>
        public static string CannotBeMinus {
            get {
                return ResourceManager.GetString("CannotBeMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not Join.
        /// </summary>
        public static string CouldNotJoin {
            get {
                return ResourceManager.GetString("CouldNotJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password you have entered was invalid. Please try again later..
        /// </summary>
        public static string InvalidPasswordPleaseTryAgain {
            get {
                return ResourceManager.GetString("InvalidPasswordPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max reached..
        /// </summary>
        public static string MaxReached {
            get {
                return ResourceManager.GetString("MaxReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message to report is sent by you..
        /// </summary>
        public static string MessageToReportIsSentByYou {
            get {
                return ResourceManager.GetString("MessageToReportIsSentByYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message to report is not found..
        /// </summary>
        public static string MessageToReportNotFound {
            get {
                return ResourceManager.GetString("MessageToReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already taken. Try another..
        /// </summary>
        public static string NotUnique {
            get {
                return ResourceManager.GetString("NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, do not kick test. :(.
        /// </summary>
        public static string PleaseDoNotKickTest {
            get {
                return ResourceManager.GetString("PleaseDoNotKickTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A room is full, busy or closed..
        /// </summary>
        public static string RoomIsFullBusyOrEnded {
            get {
                return ResourceManager.GetString("RoomIsFullBusyOrEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully reported. Thank you..
        /// </summary>
        public static string SuccessfullyReportedThankYou {
            get {
                return ResourceManager.GetString("SuccessfullyReportedThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum must be {0}..
        /// </summary>
        public static string SumMustBeA {
            get {
                return ResourceManager.GetString("SumMustBeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TITLE_Error {
            get {
                return ResourceManager.GetString("TITLE_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string TITLE_Success {
            get {
                return ResourceManager.GetString("TITLE_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werewolves must be smaller than a half of the total..
        /// </summary>
        public static string WerewolvesMustBeSmallerThanHalfOfTotal {
            get {
                return ResourceManager.GetString("WerewolvesMustBeSmallerThanHalfOfTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are banned..
        /// </summary>
        public static string YouAreBanned {
            get {
                return ResourceManager.GetString("YouAreBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are banned by the room master. Try another room..
        /// </summary>
        public static string YouAreBannedByRoomMaster {
            get {
                return ResourceManager.GetString("YouAreBannedByRoomMaster", resourceCulture);
            }
        }
    }
}
