//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _FemaleName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _FemaleName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources._FemaleName", typeof(_FemaleName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbie.
        /// </summary>
        public static string Abbie {
            get {
                return ResourceManager.GetString("Abbie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abigail.
        /// </summary>
        public static string Abigail {
            get {
                return ResourceManager.GetString("Abigail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ada.
        /// </summary>
        public static string Ada {
            get {
                return ResourceManager.GetString("Ada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adela.
        /// </summary>
        public static string Adela {
            get {
                return ResourceManager.GetString("Adela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adelaide.
        /// </summary>
        public static string Adelaide {
            get {
                return ResourceManager.GetString("Adelaide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adele.
        /// </summary>
        public static string Adele {
            get {
                return ResourceManager.GetString("Adele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adeline.
        /// </summary>
        public static string Adeline {
            get {
                return ResourceManager.GetString("Adeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agatha.
        /// </summary>
        public static string Agatha {
            get {
                return ResourceManager.GetString("Agatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agnes.
        /// </summary>
        public static string Agnes {
            get {
                return ResourceManager.GetString("Agnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aileen.
        /// </summary>
        public static string Aileen {
            get {
                return ResourceManager.GetString("Aileen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aimee.
        /// </summary>
        public static string Aimee {
            get {
                return ResourceManager.GetString("Aimee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        public static string Alberta {
            get {
                return ResourceManager.GetString("Alberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alda.
        /// </summary>
        public static string Alda {
            get {
                return ResourceManager.GetString("Alda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexandra.
        /// </summary>
        public static string Alexandra {
            get {
                return ResourceManager.GetString("Alexandra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alice.
        /// </summary>
        public static string Alice {
            get {
                return ResourceManager.GetString("Alice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alicia.
        /// </summary>
        public static string Alicia {
            get {
                return ResourceManager.GetString("Alicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber.
        /// </summary>
        public static string Amber {
            get {
                return ResourceManager.GetString("Amber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amelia.
        /// </summary>
        public static string Amelia {
            get {
                return ResourceManager.GetString("Amelia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amy.
        /// </summary>
        public static string Amy {
            get {
                return ResourceManager.GetString("Amy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana.
        /// </summary>
        public static string Ana {
            get {
                return ResourceManager.GetString("Ana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrea.
        /// </summary>
        public static string Andrea {
            get {
                return ResourceManager.GetString("Andrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angela.
        /// </summary>
        public static string Angela {
            get {
                return ResourceManager.GetString("Angela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angelia.
        /// </summary>
        public static string Angelia {
            get {
                return ResourceManager.GetString("Angelia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angelica.
        /// </summary>
        public static string Angelica {
            get {
                return ResourceManager.GetString("Angelica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angelina.
        /// </summary>
        public static string Angelina {
            get {
                return ResourceManager.GetString("Angelina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angeline.
        /// </summary>
        public static string Angeline {
            get {
                return ResourceManager.GetString("Angeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anita.
        /// </summary>
        public static string Anita {
            get {
                return ResourceManager.GetString("Anita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ann.
        /// </summary>
        public static string Ann {
            get {
                return ResourceManager.GetString("Ann", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anna.
        /// </summary>
        public static string Anna {
            get {
                return ResourceManager.GetString("Anna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annabel.
        /// </summary>
        public static string Annabel {
            get {
                return ResourceManager.GetString("Annabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annabella.
        /// </summary>
        public static string Annabella {
            get {
                return ResourceManager.GetString("Annabella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anne.
        /// </summary>
        public static string Anne {
            get {
                return ResourceManager.GetString("Anne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annie.
        /// </summary>
        public static string Annie {
            get {
                return ResourceManager.GetString("Annie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthonia.
        /// </summary>
        public static string Anthonia {
            get {
                return ResourceManager.GetString("Anthonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antonia.
        /// </summary>
        public static string Antonia {
            get {
                return ResourceManager.GetString("Antonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabella.
        /// </summary>
        public static string Arabella {
            get {
                return ResourceManager.GetString("Arabella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ariel.
        /// </summary>
        public static string Ariel {
            get {
                return ResourceManager.GetString("Ariel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arlene.
        /// </summary>
        public static string Arlene {
            get {
                return ResourceManager.GetString("Arlene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashley.
        /// </summary>
        public static string Ashley {
            get {
                return ResourceManager.GetString("Ashley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audrey.
        /// </summary>
        public static string Audrey {
            get {
                return ResourceManager.GetString("Audrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augusta.
        /// </summary>
        public static string Augusta {
            get {
                return ResourceManager.GetString("Augusta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurelia.
        /// </summary>
        public static string Aurelia {
            get {
                return ResourceManager.GetString("Aurelia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averil.
        /// </summary>
        public static string Averil {
            get {
                return ResourceManager.GetString("Averil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbara.
        /// </summary>
        public static string Barbara {
            get {
                return ResourceManager.GetString("Barbara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beatrice.
        /// </summary>
        public static string Beatrice {
            get {
                return ResourceManager.GetString("Beatrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beatrix.
        /// </summary>
        public static string Beatrix {
            get {
                return ResourceManager.GetString("Beatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becky.
        /// </summary>
        public static string Becky {
            get {
                return ResourceManager.GetString("Becky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belinda.
        /// </summary>
        public static string Belinda {
            get {
                return ResourceManager.GetString("Belinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bella.
        /// </summary>
        public static string Bella {
            get {
                return ResourceManager.GetString("Bella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bertha.
        /// </summary>
        public static string Bertha {
            get {
                return ResourceManager.GetString("Bertha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betty.
        /// </summary>
        public static string Betty {
            get {
                return ResourceManager.GetString("Betty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beverley.
        /// </summary>
        public static string Beverley {
            get {
                return ResourceManager.GetString("Beverley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beverly.
        /// </summary>
        public static string Beverly {
            get {
                return ResourceManager.GetString("Beverly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blythe.
        /// </summary>
        public static string Blythe {
            get {
                return ResourceManager.GetString("Blythe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonnie.
        /// </summary>
        public static string Bonnie {
            get {
                return ResourceManager.GetString("Bonnie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brenda.
        /// </summary>
        public static string Brenda {
            get {
                return ResourceManager.GetString("Brenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brianna.
        /// </summary>
        public static string Brianna {
            get {
                return ResourceManager.GetString("Brianna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridget.
        /// </summary>
        public static string Bridget {
            get {
                return ResourceManager.GetString("Bridget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brigid.
        /// </summary>
        public static string Brigid {
            get {
                return ResourceManager.GetString("Brigid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britney.
        /// </summary>
        public static string Britney {
            get {
                return ResourceManager.GetString("Britney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brittany.
        /// </summary>
        public static string Brittany {
            get {
                return ResourceManager.GetString("Brittany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calista.
        /// </summary>
        public static string Calista {
            get {
                return ResourceManager.GetString("Calista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameron.
        /// </summary>
        public static string Cameron {
            get {
                return ResourceManager.GetString("Cameron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camilla.
        /// </summary>
        public static string Camilla {
            get {
                return ResourceManager.GetString("Camilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carey.
        /// </summary>
        public static string Carey {
            get {
                return ResourceManager.GetString("Carey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carla.
        /// </summary>
        public static string Carla {
            get {
                return ResourceManager.GetString("Carla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carlie.
        /// </summary>
        public static string Carlie {
            get {
                return ResourceManager.GetString("Carlie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carol.
        /// </summary>
        public static string Carol {
            get {
                return ResourceManager.GetString("Carol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carolina.
        /// </summary>
        public static string Carolina {
            get {
                return ResourceManager.GetString("Carolina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caroline.
        /// </summary>
        public static string Caroline {
            get {
                return ResourceManager.GetString("Caroline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carolyn.
        /// </summary>
        public static string Carolyn {
            get {
                return ResourceManager.GetString("Carolyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casey.
        /// </summary>
        public static string Casey {
            get {
                return ResourceManager.GetString("Casey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catherine.
        /// </summary>
        public static string Catherine {
            get {
                return ResourceManager.GetString("Catherine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cecilia.
        /// </summary>
        public static string Cecilia {
            get {
                return ResourceManager.GetString("Cecilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cecily.
        /// </summary>
        public static string Cecily {
            get {
                return ResourceManager.GetString("Cecily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celeste.
        /// </summary>
        public static string Celeste {
            get {
                return ResourceManager.GetString("Celeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celestia.
        /// </summary>
        public static string Celestia {
            get {
                return ResourceManager.GetString("Celestia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlotte.
        /// </summary>
        public static string Charlotte {
            get {
                return ResourceManager.GetString("Charlotte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chelsea.
        /// </summary>
        public static string Chelsea {
            get {
                return ResourceManager.GetString("Chelsea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cherie.
        /// </summary>
        public static string Cherie {
            get {
                return ResourceManager.GetString("Cherie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cherry.
        /// </summary>
        public static string Cherry {
            get {
                return ResourceManager.GetString("Cherry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheryl.
        /// </summary>
        public static string Cheryl {
            get {
                return ResourceManager.GetString("Cheryl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chloe.
        /// </summary>
        public static string Chloe {
            get {
                return ResourceManager.GetString("Chloe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian.
        /// </summary>
        public static string Christian {
            get {
                return ResourceManager.GetString("Christian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christiana.
        /// </summary>
        public static string Christiana {
            get {
                return ResourceManager.GetString("Christiana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christina.
        /// </summary>
        public static string Christina {
            get {
                return ResourceManager.GetString("Christina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christine.
        /// </summary>
        public static string Christine {
            get {
                return ResourceManager.GetString("Christine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cindy.
        /// </summary>
        public static string Cindy {
            get {
                return ResourceManager.GetString("Cindy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claire.
        /// </summary>
        public static string Claire {
            get {
                return ResourceManager.GetString("Claire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clara.
        /// </summary>
        public static string Clara {
            get {
                return ResourceManager.GetString("Clara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarissa.
        /// </summary>
        public static string Clarissa {
            get {
                return ResourceManager.GetString("Clarissa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claudia.
        /// </summary>
        public static string Claudia {
            get {
                return ResourceManager.GetString("Claudia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clementine.
        /// </summary>
        public static string Clementine {
            get {
                return ResourceManager.GetString("Clementine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleen.
        /// </summary>
        public static string Colleen {
            get {
                return ResourceManager.GetString("Colleen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connie.
        /// </summary>
        public static string Connie {
            get {
                return ResourceManager.GetString("Connie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Constance {
            get {
                return ResourceManager.GetString("Constance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Cordelia {
            get {
                return ResourceManager.GetString("Cordelia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corinna {
            get {
                return ResourceManager.GetString("Corinna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Courtney {
            get {
                return ResourceManager.GetString("Courtney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Crystal {
            get {
                return ResourceManager.GetString("Crystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Cyndy {
            get {
                return ResourceManager.GetString("Cyndy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Cynthia {
            get {
                return ResourceManager.GetString("Cynthia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Daisy {
            get {
                return ResourceManager.GetString("Daisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dana {
            get {
                return ResourceManager.GetString("Dana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Danielle {
            get {
                return ResourceManager.GetString("Danielle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Daphne {
            get {
                return ResourceManager.GetString("Daphne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Darcey {
            get {
                return ResourceManager.GetString("Darcey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Darla {
            get {
                return ResourceManager.GetString("Darla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Darleen {
            get {
                return ResourceManager.GetString("Darleen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Darlene {
            get {
                return ResourceManager.GetString("Darlene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Deanna {
            get {
                return ResourceManager.GetString("Deanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Debbie {
            get {
                return ResourceManager.GetString("Debbie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Deborah {
            get {
                return ResourceManager.GetString("Deborah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Delia {
            get {
                return ResourceManager.GetString("Delia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Denise {
            get {
                return ResourceManager.GetString("Denise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Diana {
            get {
                return ResourceManager.GetString("Diana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Diane {
            get {
                return ResourceManager.GetString("Diane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dianne {
            get {
                return ResourceManager.GetString("Dianne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dolly {
            get {
                return ResourceManager.GetString("Dolly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Donna {
            get {
                return ResourceManager.GetString("Donna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Doreen {
            get {
                return ResourceManager.GetString("Doreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Doris {
            get {
                return ResourceManager.GetString("Doris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dorothy {
            get {
                return ResourceManager.GetString("Dorothy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dulcie {
            get {
                return ResourceManager.GetString("Dulcie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eden {
            get {
                return ResourceManager.GetString("Eden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Edith {
            get {
                return ResourceManager.GetString("Edith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Edythe {
            get {
                return ResourceManager.GetString("Edythe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eileen {
            get {
                return ResourceManager.GetString("Eileen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Elaine {
            get {
                return ResourceManager.GetString("Elaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eleanor {
            get {
                return ResourceManager.GetString("Eleanor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eleanora {
            get {
                return ResourceManager.GetString("Eleanora", resourceCulture);
            }
        }
    }
}
