//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _MaleName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _MaleName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources._MaleName", typeof(_MaleName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron.
        /// </summary>
        public static string Aaron {
            get {
                return ResourceManager.GetString("Aaron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abel.
        /// </summary>
        public static string Abel {
            get {
                return ResourceManager.GetString("Abel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abraham.
        /// </summary>
        public static string Abraham {
            get {
                return ResourceManager.GetString("Abraham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abram.
        /// </summary>
        public static string Abram {
            get {
                return ResourceManager.GetString("Abram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adam.
        /// </summary>
        public static string Adam {
            get {
                return ResourceManager.GetString("Adam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adelbert.
        /// </summary>
        public static string Adelbert {
            get {
                return ResourceManager.GetString("Adelbert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adolf.
        /// </summary>
        public static string Adolf {
            get {
                return ResourceManager.GetString("Adolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adolph.
        /// </summary>
        public static string Adolph {
            get {
                return ResourceManager.GetString("Adolph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adolphus.
        /// </summary>
        public static string Adolphus {
            get {
                return ResourceManager.GetString("Adolphus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adrian.
        /// </summary>
        public static string Adrian {
            get {
                return ResourceManager.GetString("Adrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alan.
        /// </summary>
        public static string Alan {
            get {
                return ResourceManager.GetString("Alan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alastair.
        /// </summary>
        public static string Alastair {
            get {
                return ResourceManager.GetString("Alastair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albert.
        /// </summary>
        public static string Albert {
            get {
                return ResourceManager.GetString("Albert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alex.
        /// </summary>
        public static string Alex {
            get {
                return ResourceManager.GetString("Alex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexander.
        /// </summary>
        public static string Alexander {
            get {
                return ResourceManager.GetString("Alexander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexis.
        /// </summary>
        public static string Alexis {
            get {
                return ResourceManager.GetString("Alexis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alf.
        /// </summary>
        public static string Alf {
            get {
                return ResourceManager.GetString("Alf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfie.
        /// </summary>
        public static string Alfie {
            get {
                return ResourceManager.GetString("Alfie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfonse.
        /// </summary>
        public static string Alfonse {
            get {
                return ResourceManager.GetString("Alfonse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred.
        /// </summary>
        public static string Alfred {
            get {
                return ResourceManager.GetString("Alfred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algernon.
        /// </summary>
        public static string Algernon {
            get {
                return ResourceManager.GetString("Algernon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allan.
        /// </summary>
        public static string Allan {
            get {
                return ResourceManager.GetString("Allan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allen.
        /// </summary>
        public static string Allen {
            get {
                return ResourceManager.GetString("Allen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphonse.
        /// </summary>
        public static string Alphonse {
            get {
                return ResourceManager.GetString("Alphonse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alvin.
        /// </summary>
        public static string Alvin {
            get {
                return ResourceManager.GetString("Alvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambrose.
        /// </summary>
        public static string Ambrose {
            get {
                return ResourceManager.GetString("Ambrose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrew.
        /// </summary>
        public static string Andrew {
            get {
                return ResourceManager.GetString("Andrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andy.
        /// </summary>
        public static string Andy {
            get {
                return ResourceManager.GetString("Andy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthony.
        /// </summary>
        public static string Anthony {
            get {
                return ResourceManager.GetString("Anthony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anton.
        /// </summary>
        public static string Anton {
            get {
                return ResourceManager.GetString("Anton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archibald.
        /// </summary>
        public static string Archibald {
            get {
                return ResourceManager.GetString("Archibald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ariel.
        /// </summary>
        public static string Ariel {
            get {
                return ResourceManager.GetString("Ariel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arman.
        /// </summary>
        public static string Arman {
            get {
                return ResourceManager.GetString("Arman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armand.
        /// </summary>
        public static string Armand {
            get {
                return ResourceManager.GetString("Armand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armin.
        /// </summary>
        public static string Armin {
            get {
                return ResourceManager.GetString("Armin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arnold.
        /// </summary>
        public static string Arnold {
            get {
                return ResourceManager.GetString("Arnold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arthur.
        /// </summary>
        public static string Arthur {
            get {
                return ResourceManager.GetString("Arthur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashley.
        /// </summary>
        public static string Ashley {
            get {
                return ResourceManager.GetString("Ashley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashton.
        /// </summary>
        public static string Ashton {
            get {
                return ResourceManager.GetString("Ashton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aubrey.
        /// </summary>
        public static string Aubrey {
            get {
                return ResourceManager.GetString("Aubrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augustus.
        /// </summary>
        public static string Augustus {
            get {
                return ResourceManager.GetString("Augustus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylmer.
        /// </summary>
        public static string Aylmer {
            get {
                return ResourceManager.GetString("Aylmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacchus.
        /// </summary>
        public static string Bacchus {
            get {
                return ResourceManager.GetString("Bacchus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baldwin.
        /// </summary>
        public static string Baldwin {
            get {
                return ResourceManager.GetString("Baldwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barnaby.
        /// </summary>
        public static string Barnaby {
            get {
                return ResourceManager.GetString("Barnaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barnard.
        /// </summary>
        public static string Barnard {
            get {
                return ResourceManager.GetString("Barnard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barry.
        /// </summary>
        public static string Barry {
            get {
                return ResourceManager.GetString("Barry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bartholomew.
        /// </summary>
        public static string Bartholomew {
            get {
                return ResourceManager.GetString("Bartholomew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bartlemy.
        /// </summary>
        public static string Bartlemy {
            get {
                return ResourceManager.GetString("Bartlemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basil.
        /// </summary>
        public static string Basil {
            get {
                return ResourceManager.GetString("Basil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben.
        /// </summary>
        public static string Ben {
            get {
                return ResourceManager.GetString("Ben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benedict.
        /// </summary>
        public static string Benedict {
            get {
                return ResourceManager.GetString("Benedict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benjamin.
        /// </summary>
        public static string Benjamin {
            get {
                return ResourceManager.GetString("Benjamin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bennet.
        /// </summary>
        public static string Bennet {
            get {
                return ResourceManager.GetString("Bennet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bernard.
        /// </summary>
        public static string Bernard {
            get {
                return ResourceManager.GetString("Bernard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bernhard.
        /// </summary>
        public static string Bernhard {
            get {
                return ResourceManager.GetString("Bernhard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bert.
        /// </summary>
        public static string Bert {
            get {
                return ResourceManager.GetString("Bert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bertrand.
        /// </summary>
        public static string Bertrand {
            get {
                return ResourceManager.GetString("Bertrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billy.
        /// </summary>
        public static string Billy {
            get {
                return ResourceManager.GetString("Billy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob.
        /// </summary>
        public static string Bob {
            get {
                return ResourceManager.GetString("Bob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bobby.
        /// </summary>
        public static string Bobby {
            get {
                return ResourceManager.GetString("Bobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brad.
        /// </summary>
        public static string Brad {
            get {
                return ResourceManager.GetString("Brad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bradley.
        /// </summary>
        public static string Bradley {
            get {
                return ResourceManager.GetString("Bradley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brandon.
        /// </summary>
        public static string Brandon {
            get {
                return ResourceManager.GetString("Brandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brendan.
        /// </summary>
        public static string Brendan {
            get {
                return ResourceManager.GetString("Brendan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brent.
        /// </summary>
        public static string Brent {
            get {
                return ResourceManager.GetString("Brent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brett.
        /// </summary>
        public static string Brett {
            get {
                return ResourceManager.GetString("Brett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brian.
        /// </summary>
        public static string Brian {
            get {
                return ResourceManager.GetString("Brian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruce.
        /// </summary>
        public static string Bruce {
            get {
                return ResourceManager.GetString("Bruce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruno.
        /// </summary>
        public static string Bruno {
            get {
                return ResourceManager.GetString("Bruno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bryan.
        /// </summary>
        public static string Bryan {
            get {
                return ResourceManager.GetString("Bryan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byron.
        /// </summary>
        public static string Byron {
            get {
                return ResourceManager.GetString("Byron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caesar.
        /// </summary>
        public static string Caesar {
            get {
                return ResourceManager.GetString("Caesar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calvin.
        /// </summary>
        public static string Calvin {
            get {
                return ResourceManager.GetString("Calvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameron.
        /// </summary>
        public static string Cameron {
            get {
                return ResourceManager.GetString("Cameron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carey.
        /// </summary>
        public static string Carey {
            get {
                return ResourceManager.GetString("Carey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carl.
        /// </summary>
        public static string Carl {
            get {
                return ResourceManager.GetString("Carl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carles.
        /// </summary>
        public static string Carles {
            get {
                return ResourceManager.GetString("Carles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carlie.
        /// </summary>
        public static string Carlie {
            get {
                return ResourceManager.GetString("Carlie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carol.
        /// </summary>
        public static string Carol {
            get {
                return ResourceManager.GetString("Carol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casey.
        /// </summary>
        public static string Casey {
            get {
                return ResourceManager.GetString("Casey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cecil.
        /// </summary>
        public static string Cecil {
            get {
                return ResourceManager.GetString("Cecil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cedric.
        /// </summary>
        public static string Cedric {
            get {
                return ResourceManager.GetString("Cedric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chad.
        /// </summary>
        public static string Chad {
            get {
                return ResourceManager.GetString("Chad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chester.
        /// </summary>
        public static string Chester {
            get {
                return ResourceManager.GetString("Chester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chris.
        /// </summary>
        public static string Chris {
            get {
                return ResourceManager.GetString("Chris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian.
        /// </summary>
        public static string Christian {
            get {
                return ResourceManager.GetString("Christian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christopher.
        /// </summary>
        public static string Christopher {
            get {
                return ResourceManager.GetString("Christopher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarence.
        /// </summary>
        public static string Clarence {
            get {
                return ResourceManager.GetString("Clarence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clark.
        /// </summary>
        public static string Clark {
            get {
                return ResourceManager.GetString("Clark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clifford.
        /// </summary>
        public static string Clifford {
            get {
                return ResourceManager.GetString("Clifford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clive.
        /// </summary>
        public static string Clive {
            get {
                return ResourceManager.GetString("Clive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clyde.
        /// </summary>
        public static string Clyde {
            get {
                return ResourceManager.GetString("Clyde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cody.
        /// </summary>
        public static string Cody {
            get {
                return ResourceManager.GetString("Cody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colin.
        /// </summary>
        public static string Colin {
            get {
                return ResourceManager.GetString("Colin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conan.
        /// </summary>
        public static string Conan {
            get {
                return ResourceManager.GetString("Conan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conrad.
        /// </summary>
        public static string Conrad {
            get {
                return ResourceManager.GetString("Conrad", resourceCulture);
            }
        }
    }
}
