//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources._Title", typeof(_Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemist.
        /// </summary>
        public static string Alchemist {
            get {
                return ResourceManager.GetString("Alchemist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ale Brewer.
        /// </summary>
        public static string AleBrewer {
            get {
                return ResourceManager.GetString("AleBrewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anarchist.
        /// </summary>
        public static string Anarchist {
            get {
                return ResourceManager.GetString("Anarchist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aristocrat.
        /// </summary>
        public static string Aristocrat {
            get {
                return ResourceManager.GetString("Aristocrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baker.
        /// </summary>
        public static string Baker {
            get {
                return ResourceManager.GetString("Baker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer Brewer.
        /// </summary>
        public static string BeerBrewer {
            get {
                return ResourceManager.GetString("BeerBrewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishop.
        /// </summary>
        public static string Bishop {
            get {
                return ResourceManager.GetString("Bishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacksmith.
        /// </summary>
        public static string Blacksmith {
            get {
                return ResourceManager.GetString("Blacksmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bricklayer.
        /// </summary>
        public static string Bricklayer {
            get {
                return ResourceManager.GetString("Bricklayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string Carrier {
            get {
                return ResourceManager.GetString("Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Builder.
        /// </summary>
        public static string CastleEngineer {
            get {
                return ResourceManager.GetString("CastleEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamberlain.
        /// </summary>
        public static string Chamberlain {
            get {
                return ResourceManager.GetString("Chamberlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleric.
        /// </summary>
        public static string Cleric {
            get {
                return ResourceManager.GetString("Cleric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clown.
        /// </summary>
        public static string Clown {
            get {
                return ResourceManager.GetString("Clown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coachman.
        /// </summary>
        public static string Coachman {
            get {
                return ResourceManager.GetString("Coachman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook.
        /// </summary>
        public static string Cook {
            get {
                return ResourceManager.GetString("Cook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detective.
        /// </summary>
        public static string Detective {
            get {
                return ResourceManager.GetString("Detective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyper.
        /// </summary>
        public static string Dyer {
            get {
                return ResourceManager.GetString("Dyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer.
        /// </summary>
        public static string Farmer {
            get {
                return ResourceManager.GetString("Farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisher.
        /// </summary>
        public static string Fisher {
            get {
                return ResourceManager.GetString("Fisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Florist.
        /// </summary>
        public static string Florist {
            get {
                return ResourceManager.GetString("Florist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forester.
        /// </summary>
        public static string Forester {
            get {
                return ResourceManager.GetString("Forester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grave Keeper.
        /// </summary>
        public static string GraveKeeper {
            get {
                return ResourceManager.GetString("GraveKeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocer.
        /// </summary>
        public static string Grocer {
            get {
                return ResourceManager.GetString("Grocer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay Merchant.
        /// </summary>
        public static string HayMerchant {
            get {
                return ResourceManager.GetString("HayMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse-gear Craftman.
        /// </summary>
        public static string HorseGearCraftman {
            get {
                return ResourceManager.GetString("HorseGearCraftman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injured Soldier.
        /// </summary>
        public static string InjuredSoldier {
            get {
                return ResourceManager.GetString("InjuredSoldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innkeeper.
        /// </summary>
        public static string Innkeeper {
            get {
                return ResourceManager.GetString("Innkeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquisitor.
        /// </summary>
        public static string Inquisitor {
            get {
                return ResourceManager.GetString("Inquisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge.
        /// </summary>
        public static string Judge {
            get {
                return ResourceManager.GetString("Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leather Craftman.
        /// </summary>
        public static string LeatherCraftman {
            get {
                return ResourceManager.GetString("LeatherCraftman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumberjack.
        /// </summary>
        public static string Lumberjack {
            get {
                return ResourceManager.GetString("Lumberjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magistrate.
        /// </summary>
        public static string Magistrate {
            get {
                return ResourceManager.GetString("Magistrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercenary.
        /// </summary>
        public static string Mercenary {
            get {
                return ResourceManager.GetString("Mercenary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string Merchant {
            get {
                return ResourceManager.GetString("Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miller.
        /// </summary>
        public static string Miller {
            get {
                return ResourceManager.GetString("Miller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneylender.
        /// </summary>
        public static string Moneylender {
            get {
                return ResourceManager.GetString("Moneylender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk.
        /// </summary>
        public static string Monk {
            get {
                return ResourceManager.GetString("Monk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomad.
        /// </summary>
        public static string Nomad {
            get {
                return ResourceManager.GetString("Nomad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official.
        /// </summary>
        public static string Official {
            get {
                return ResourceManager.GetString("Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldKnight.
        /// </summary>
        public static string OldKnight {
            get {
                return ResourceManager.GetString("OldKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimist.
        /// </summary>
        public static string Optimist {
            get {
                return ResourceManager.GetString("Optimist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacifist.
        /// </summary>
        public static string Pacifist {
            get {
                return ResourceManager.GetString("Pacifist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painter.
        /// </summary>
        public static string Painter {
            get {
                return ResourceManager.GetString("Painter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastor.
        /// </summary>
        public static string Pastor {
            get {
                return ResourceManager.GetString("Pastor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peddler.
        /// </summary>
        public static string Peddler {
            get {
                return ResourceManager.GetString("Peddler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacist.
        /// </summary>
        public static string Pharmacist {
            get {
                return ResourceManager.GetString("Pharmacist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philosopher.
        /// </summary>
        public static string Philosopher {
            get {
                return ResourceManager.GetString("Philosopher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilgrim.
        /// </summary>
        public static string Pilgrim {
            get {
                return ResourceManager.GetString("Pilgrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pioneer.
        /// </summary>
        public static string Pioneer {
            get {
                return ResourceManager.GetString("Pioneer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potter.
        /// </summary>
        public static string Potter {
            get {
                return ResourceManager.GetString("Potter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priest.
        /// </summary>
        public static string Priest {
            get {
                return ResourceManager.GetString("Priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prison Guard.
        /// </summary>
        public static string PrisonGuard {
            get {
                return ResourceManager.GetString("PrisonGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Teacher.
        /// </summary>
        public static string PrivateTeacher {
            get {
                return ResourceManager.GetString("PrivateTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar.
        /// </summary>
        public static string Scholar {
            get {
                return ResourceManager.GetString("Scholar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Agent.
        /// </summary>
        public static string SecretAgent {
            get {
                return ResourceManager.GetString("SecretAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Guard.
        /// </summary>
        public static string SecurityGuard {
            get {
                return ResourceManager.GetString("SecurityGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settler.
        /// </summary>
        public static string Settler {
            get {
                return ResourceManager.GetString("Settler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shepherd.
        /// </summary>
        public static string Shepherd {
            get {
                return ResourceManager.GetString("Shepherd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Builder.
        /// </summary>
        public static string ShipBuilder {
            get {
                return ResourceManager.GetString("ShipBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siege Engineer.
        /// </summary>
        public static string SiegeEngineer {
            get {
                return ResourceManager.GetString("SiegeEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silk Tailor.
        /// </summary>
        public static string SilkTailor {
            get {
                return ResourceManager.GetString("SilkTailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailor.
        /// </summary>
        public static string Tailor {
            get {
                return ResourceManager.GetString("Tailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveler.
        /// </summary>
        public static string Traveler {
            get {
                return ResourceManager.GetString("Traveler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valet.
        /// </summary>
        public static string Valet {
            get {
                return ResourceManager.GetString("Valet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village Chief.
        /// </summary>
        public static string VillageChief {
            get {
                return ResourceManager.GetString("VillageChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine Brewer.
        /// </summary>
        public static string WineBrewer {
            get {
                return ResourceManager.GetString("WineBrewer", resourceCulture);
            }
        }
    }
}
